### ISSUE TITLE
New window does not replace the existing window

### ISSUE THREAD

**Issue by WhyNotHugo** [NomisIV/swayhide#1]
Say I have a vertical split like so:

```
| terminal | tabbed[multiple windows] |
```

If I run `swayhide something` on my terminal, the terminal disappears, and the
new window appears as a child of the container on the right.

I kind of expected `swayhide` to _replace_ my current window with the new one,
rather than spawn the new one elsewhere.

I think this can be achieved by:

- mark original window
- split h
- spawn new window
- move marked to scratchpad
- split none

The result is that the new window is dropped into the same place as the
original one, with affecting the exterior layout at all.

What are your thoughts on this? Does the idea/feature/change make sense?

**Comment by NomisIV** [comment]
The ideal behavior is indeed to replace the window, but I haven't been able to figure out how to do it in all scenarios. Currently the program spawns the child command before hiding the terminal, which can lead to unpredictable behavior:

In one case, the new window may open *before* the terminal is hidden. In this case the window will spawn as a child of the terminal, since the terminal is still the focused window at spawn.

In the second case, the new window opens *after* the terminal is hidden. In this case the focused window will change to the other window group, since they are the only windows left. So when the new window spawns, it will spawn as a child to the other group, instead of being a child of the terminal itself.

I guess the real solution to this would be to wait until the child window has spawned, before hiding the terminal. Or perhaps moving the new window to the same mark as the one set by the old window.

Please let me know if I've got something wrong. I don't really know anything more about sway than I had to to write this program.

Also, feel free to send a PR if you manage to make something that works better. I might find some time to personally look into this again, but cannot leave any deadlines.
