### ISSUE TITLE
Fish shell completions

### ISSUE THREAD

**Issue by tosti007** [NomisIV/swayhide#4]
Hey there!

Currently there are no shell completions for swayhide, since I am a fish-shell user I thought I'd write my own and share them here.

I am making this an issue instead of a PR as I'm unsure where and wether or not you want this in the repo.

The full completion file `swayhide.fish`:
```fish
#
# Completions for swayhide
#

complete -c swayhide -s h -l help -d "Display help and exit"
complete -c swayhide -xa "(__fish_complete_subcommand)"
```

**Comment by NomisIV** [comment]
This is looking great, and I'd love to package completions for all shells at some point!

The only problem I see is packaging the completion(s) with the rest of the program. The "official" installation method is using cargo, and I don't think it supports installing anything else than the actual rust binaries. So as I see it, completions require packaging. This is something I would like to avoid due to the extra overhead when bumping versions, but I see how it's most likely the only way forward.

swayhide is already in the AUR, but the install script would have to be modified. I'll let @WhyNotHugo know of that. I could also fix a nix flake, or possibly integration into nixpkgs for NixOS support. What distro are you running?

**Comment by WhyNotHugo** [comment]
Cargo has no facilities to install this kind of thing. There's an open issue for it, but I don't expect it to change any time soon.

For distribution packages, it's trivial for packages to install this into the right location.

The usual approach is to just include it in `contrib/` in the repo. Ping me if you add completions and I'll update the AUR package.

**Comment by ghost** [comment]
completions would be nice, [clap 3.0.0-beta](https://docs.rs/clap_generate/3.0.0-rc.8/clap_generate/)  has some stuff related to generating them but a `/contrib` would a fine way to handle 
*edit: updated link

**Comment by NomisIV** [comment]
@WhyNotHugo Completions are added now :)

**Comment by tosti007** [comment]
Hey there, thanks for adding it to the repo! About how to bundle the completions: I think the distro-specific package maintainers themselves should handle that, but I think it would be nice for the next releases to add the completion files within the release folder, as it allows the maintainers to download it all in one go and for the completions to be in sync with the releases.

**Comment by NomisIV** [comment]
What release folder do you mean? The `target/release` folder after building the rust project with `cargo build --release`?
